config/routes.rb
Jobsy::Application.routes.draw do
  get "home/index"
  get "home/search"

  root :to => 'home#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  has_many :jobs
end

app/models/city.rb
class City < ActiveRecord::Base
  attr_accessible :name
  validates :name, :presence => true
  
  has_many :jobs

  def self.city_not_specified
    City.find_by_name("Not-Specified").try(:id)
  end
  
end

app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessible :advert_link, :category_id, :city_id, :pay_heigh, :pay_low, :posted_date, :seek_id, :title
  
  belongs_to :city
  belongs_to :category
 
  validates :seek_id, :presence => true
  validates :category_id, :presence => true
  validates :advert_link, :presence => true
  validates :posted_date, :presence => true

  scope :by_category, lambda {|category|
    {
      :joins => :category,
      :conditions => "categories.name = '#{category}'",
      :order => "posted_date desc"}  
  }
  
  scope :between_last_month, lambda {
    {:conditions => {:created_at => (((Date.today - 1.month) - 1)..(Date.today + 1))}}
  }
  
  scope :latest_10, lambda {
    {:limit => 10}
  }
  
  scope :order, lambda {
    {:order => "id desc"}
  }
  
  before_create :assign_city
  
  def self.jobs_by_category(category)
    job_list = []
    jobs = Job.by_category(category).between_last_month.count(:group => 'city_id', :include => :city)
    jobs.each do |job|
      job_list << [City.find(job[0]).name, job[1]]    
    end
    job_list
  end
  
  def assign_city
    self.city_id = City.city_not_specified unless self.city_id
  end
  
  def self.latest_10_jobs(category)
    self.by_category(category).latest_10.between_last_month
  end
  
  def self.date_range
    jobs = Job.order
    [jobs.last, jobs.first]
  end


end

app/models/seek_job_reader.rb
require 'rubygems'
require 'nokogiri'
require 'date'

class SeekJobReader 
  
  attr_accessor :html
  
  def read_jobs(page, job_category)
    page = Nokogiri::HTML(RestClient.get("http://www.seek.com.au/JobSearch?DateRange=31&SearchFrom=quick&Keywords=#{job_category}&nation=3000&page=#{page}&SearchType=Paging"))
    divs = page.css('dl.l-clearfix')
    divs.each do |div|
      @seek_job = SeekJobReader.new
      @seek_job.html = div.to_html
      city_id = City.find_by_name(@seek_job.city).try(:id)
      category_id = Category.find_by_name(job_category).try(:id)
      posted_date = @seek_job.job_posted_date
      title = @seek_job.job_title
      link = @seek_job.job_advert_link
      range = @seek_job.pay_range
      job_id = @seek_job.seek_job_id
      
      unless Job.find_by_seek_id(job_id)
        new_job = Job.new
        #:advert_link, :category_id, :city_id, :pay_heigh, :pay_low, :posted_date, :seek_id, :title
        new_job.advert_link = link
        new_job.category_id = category_id
        new_job.city_id = city_id
        new_job.pay_heigh = range[1]
        new_job.pay_low = range[0]
        new_job.posted_date = posted_date
        new_job.seek_id = job_id
        new_job.title = title
        new_job.save
        p "job #{job_id} - #{job_category} saved"
      else
        p "job #{job_id} - #{job_category} already exist"
      end
      
    end
  end
  
  
  def city
    doc = Nokogiri::HTML(html)
    str = doc.css('.state-has-logo span').text #city with logo
    if str == ""
      str = doc.css('span').text
      objs = str.split(/\n/)
      objs.each do |val|
        str = search_city_name(str)  
      end
      
    end
    str
  end
  
  def job_posted_date
    dte = ""
    str_dt = ""
    doc = Nokogiri::HTML(html)
    str_dt = doc.css('.state-has-logo small').text #date with logo
    str_dt = doc.css('dd small').text if str_dt == "" #date without a logo
    
    if str_dt == "NEW"
      dte = DateTime.now
    else
      begin
        dte = Date.parse(str_dt)
      rescue
        dte = Chronic.parse(str_dt)    
      end    
    end
    dte
  end
  
  def job_title
    doc = Nokogiri::HTML(html)
    title = doc.css('h2 a').text
    title
  end
  
  def seek_job_id
    url = job_advert_link
    url.split("/").last
  end
  
  def pay_range
    range = [0,0]
    doc = Nokogiri::HTML(html)
    price = doc.css('span strong').text
    if price != ""
      amounts = price.gsub("$","").split("-")
      range[0] = amounts[0].gsub(",","").to_i if (amounts && amounts.size > 0) 
      range[1] = amounts[1].gsub(",","").to_i if (amounts && amounts.size == 2)
    end
    range
  end
  
  def job_advert_link
    #http://www.dzone.com/snippets/finding-elements-attributes
    href = ""
    doc = Nokogiri::HTML(html)
    doc = doc.css('h2 a')
    reader = Nokogiri::XML::Reader(doc.to_xml)
    elems = reader.read
    elems.each do |ele|
      if ele.name == "a"
        href = ele.attributes["href"]
      end
    end
    href
  end
 
 
  private
  def search_city_name(text)
     city = ""
     match = text.to_s.match('(Sydney|Melbourne|Brisbane|Perth)')
     if match
       city = match[0]
     end
     city
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  respond_to :js, :html
  
  before_filter :categories
  
  
  def index
    session[:key] ||= Category.first.name
    latest_10_jobs
    @jobs = Job.jobs_by_category(session[:key])
    @h = LazyHighCharts::HighChart.new('pie') do |f|
       f.options[:chart][:defaultSeriesType] = "pie"
       f.options[:title][:text] = "Searching jobs for #{session[:key]}"
       f.series(:name=> session[:key], :data=> @jobs)
    end
  end
  
  def search
    key = params[:key]
    session[:key] = params[:key]
    @jobs = Job.jobs_by_category(key)
    @h = LazyHighCharts::HighChart.new('pie') do |f|
       f.options[:chart][:defaultSeriesType] = "pie"
       f.options[:title][:text] = "Searching jobs for #{key}"
       f.series(:name=> key, :data=> @jobs)
    end
    latest_10_jobs
    @current_key = key
  end
  
  def categories
    @categories = Category.all
  end
  
  def latest_10_jobs
    @latest_jobs = Job.latest_10_jobs(session[:key])
  end
  
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def search_categories(category)
    raw "<span class='label label-info'>#{category}</span>"
  end
  
  def salary_scale(job)
    raw "#{amount(job.pay_low)} - #{amount(job.pay_heigh)}"
  end
  
  def date_range
    Job.date_range
  end
  
  private
  def amount pay
    number_to_currency(pay) if pay != 0
  end
  
end

app/views/home/_chart.html.erb
<div id="my_id"></div>
<%= high_chart("my_id", @h) %>
<div class="row">
	<div class="span3 well">
		<h4> <%= session[:key]%> Job count</h4>
		<table>
		<% @jobs.each do |job| %>
		<tr>
			<td>
				<strong>
					<%= job[1].to_s.rjust(2, '0')%>
				</strong>
				<%= job[0]%>
				
			</td>
		</tr>
		<% end %>
		</table>
	</div>
</div>

app/views/home/_latest_10_jobs.html.erb
<h4>
	Searching jobs for <%= session[:key]%>
</h4>
<table class="table table-bordered">
	<% @latest_jobs.each do |job|%> 
	<tr>
		<td>
			<span class="label label-success">
				<%= job.city.name%>
			</span>
		</td>
		<td>
			<%= link_to job.title, "http://seek.com.au#{job.advert_link}", :target => "_blank"%>
			<br />
			<p class="muted"><%= job.posted_date%></p>
		</td>
		<td>
			<%= salary_scale(job) %>
		</td>
	</tr>
	<% end %>
</table>

app/views/home/index.html.erb
<div class="row" id="navigation">
	<div class="span9">
		<% @categories.each do |category| %>
		 <%= link_to search_categories(category.name), home_search_path + "?key=#{category.name}", :remote => true %>
		<% end %> 
    </div>
</div>
<br />
<div id="job_list">
	<%= render :partial => 'latest_10_jobs'%>
</div>

app/views/home/search.js.erb
$("#dash").html("<%= raw escape_javascript(render(:partial => 'chart')) %>").show("slide", { direction: "right" }, 1000);
$("#job_list").html("<%= raw escape_javascript(render(:partial => 'latest_10_jobs')) %>").show("slide", { direction: "right" }, 1000);

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Jobsy" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
	<%= stylesheet_link_tag "http://code.jquery.com/ui/1.9.2/themes/base/jquery-ui.css", :media => "all" %>
    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%#= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%#= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%#= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%#= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%#= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Jobsy ..seek jobs..</a>
          <div class="container nav-collapse">
            
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span12">
          	<h5>
          		<% range = date_range %>
          		Date range from <%= range.first.posted_date %> to <%= range.last.posted_date %> 
          	</h5>
          </div>
          <div class="span7">
          	 <%= yield %>
          </div>
          <div class="span5">
            <div class="well sidebar-nav">
              <div class="row" id="dash">
					<%= render :partial => 'chart'%>
			  </div>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p>
        	Jobsy is extracting jobs from <a href="http:/seek.com.au">seek.com.au </a>. 	
        </p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "http://code.jquery.com/ui/1.9.2/jquery-ui.js"%>
  	<script type="text/javascript">
	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', 'UA-37863663-1']);
	  _gaq.push(['_trackPageview']);
	
	  (function() {
	    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();
	
	</script>
  </body>
</html>